#!/bin/bash

set -euxo pipefail

update-alternatives \
    --install /usr/bin/vim vim /usr/bin/vim.tiny 15
update-alternatives \
    --install /usr/bin/editor editor /usr/bin/vim.tiny 15
update-alternatives \
    --install /usr/bin/ex ex /usr/bin/vim.tiny 15
update-alternatives \
    --install /usr/bin/vi vi /usr/bin/vim.tiny 15
update-alternatives \
    --install /usr/bin/view view /usr/bin/vim.tiny 15

#DEBHELPER#

exit 0
